version: '2.1'

services:
  db:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_DB=stock_exchange
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
    expose:
      - "5432"
    ports:
      - "5432:5432"
    
  main:
    build: ./src
    user: root
    command: bash -c "make && taskset -c 0-7 ./server"
    volumes:      
      - ./src:/src
    ports:
      - "12345:12345"
    expose:
      - "12345"
    depends_on:
      - db